# Port Metadata
PORTNAME = 			SDL
PORTVERSION = 		1.2.15

# No dependencies beyond the base system.
DEPENDENCIES =

# What files we need to download, and where from.
DOWNLOAD_SITE = 	http://libsdl.org/release
DOWNLOAD_FILES = 	${PORTNAME}-${PORTVERSION}.tar.gz

TARGET =			libSDL.a
HDR_DIRECTORY =     include
HDR_INSTDIR =       SDL

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =		KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
