# Port Metadata
PORTNAME = 			liboggvorbisplay
PORTVERSION = 		2.0.0

DEPENDENCIES =      libvorbis

# What files we need to download, and where from.
GIT_REPOSITORY =    git://git.code.sf.net/p/cadcdev/liboggvorbis

TARGET =			liboggvorbisplay.a
INSTALLED_HDRS =	include/oggvorbis/sndoggvorbis.h
HDR_INSTDIR =       oggvorbis

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =		KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
