# Port Metadata
PORTNAME = 			libconio
PORTVERSION = 		2.0.0

# No dependencies beyond the base system.
DEPENDENCIES =

# What files we need to download, and where from.
GIT_REPOSITORY =    git://git.code.sf.net/p/cadcdev/libconio

TARGET =			libconio.a
INSTALLED_HDRS =	include/conio.h include/draw.h include/input.h
HDR_INSTDIR =       conio

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =		KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
